# Generated by Django 4.2.1 on 2024-01-29 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRecipeRelations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(verbose_name='Вес грамм')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Отношение "Рецепты-Продукты"',
                'verbose_name_plural': 'Отношение "Рецепты-Продукты"',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название рецепта')),
                ('products_in_recipe', models.ManyToManyField(related_name='recipes', through='cook.ProductRecipeRelations', to='cook.product', verbose_name='Состав рецепта')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='productreciperelations',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_product', to='cook.recipe', verbose_name='Рецепт'),
        ),
    ]
